name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_liquid_tab_bar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/